### ISSUE TITLE
Panels not working when running inside Docker

### ISSUE THREAD

**Issue by danielsetreus** [beyondcode/tinkerwell#7]
Tinkerwell version: 3.33.0
OS: macOS Ventura 13.4

## Steps to reproduce
`~/sites/laravel/docker-compose.yml`
```yml
version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
```

Pull a fresh Laravel into `~/sites/laravel/my-project`. 

Selecting `~/sites/laravel/` as directory in Tinkerwell, connecting through Docker, and selecting the container. Can run code, but no panels are showing.

I've also tested with custom drivers. The custom driver can boot, but will not load any panels. 

It is as if Tinkerwell is unable to execute the panels code. In custom drivers I've even added logging to a text file on the `addPanels` method, but it seems as it is never executed at all.
